# Generated by Django 3.2.5 on 2022-01-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='question1',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Mabye')], max_length=40, unique=True),
        ),
    ]
