# Generated by Django 3.2.5 on 2022-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_app', '0002_auto_20220122_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
