# Generated by Django 3.2.5 on 2022-01-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inno_app', '0004_alter_post_question1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
