# Generated by Django 3.2.5 on 2022-02-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inno_app', '0006_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
